### ISSUE TITLE
sord_validate and lv2lint fail on bsequencer

### ISSUE THREAD

**Issue by dvzrv** [sjaehn/BSEQuencer#12]
When packaging 0.4 for Arch Linux, I ran `sord_validate` ([man page](https://jlk.fjfi.cvut.cz/arch/manpages/man/sord_validate.1)) and `lv2lint` ([man page](https://jlk.fjfi.cvut.cz/arch/manpages/man/lv2lint.1)) on the plugin, which produces lots of errors:
[bsequencer-0.4-1-x86_64-check.log](https://github.com/sjaehn/BSEQuencer/files/3876728/bsequencer-0.4-1-x86_64-check.log)

**Comment by sjaehn** [comment]
Thanks for information. 

About the lv2lint output. I checked before. I (only) got 2 fails and 2 warns:
`[WARN]  Linking` - c++ libraries...
`[WARN]  Author Email` - wontfix, sorry
`[FAIL]  Version Minor` - will be fixed in version 1.x (very soon). The plugin is still in development. I do not want to guarantee full backward compatibility, yet. But soon. Promised.
`[FAIL]  Version Micro` - vide supra

About yours:
`[FAIL]  Instantiation` - Maybe related to the bug just fixed in c5c66c68b100292922e8b47b3a88a7524619bacf ?
`[FAIL]  Symbols` - Did you compile with `-fvisibility=hidden` ?
`[FAIL]  State` - I don't know. Everything should be in there. Maybe secondary to `[FAIL]  Instantiation`?

**Comment by sjaehn** [comment]
Version 1.2.0 is out now. `[FAIL] Version Minor` and `[FAIL] Version Micro` fixed (as promised).
