### ISSUE TITLE
BSEQuencer for CV waveforms?

### ISSUE THREAD

**Issue by mxmilkiib** [sjaehn/BSEQuencer#20]
There isn't really a sequencer for [CV](https://linuxmusicians.com/viewtopic.php?f=1&t=20701) yet. Might a BSEQuencer for CV (BCVQuencer? ;) be something you could be interested in?

I'm in need of something to drive my modular drum machine with :)
![image](https://user-images.githubusercontent.com/108225/82343236-7f93a180-99ea-11ea-97cb-067e1a156ad7.png)

**Comment by sjaehn** [comment]
Interesting & strange together.

It's not fully clear for me what you want. I think you want a step sequencer with two output per channel: level (= velocity) and pitch (= note). Times four (4 output channels). In total 8 output CV ports. Plus calibration controls, maybe. And two input CV ports. And then we still don't have polyphony :-(. For this, you can multiply the number of ports with the number of voices...

Another point is the core playback engine of B.SEQuencer. It is quite MIDI-orientated. It iterates through the MIDI inputs and the scheduled MIDI events instead of chronologically running through all input samples. Thus, the playback engine needs to be exchanged for CV.

**Comment by mxmilkiib** [comment]
I'm having a proper think about a sensible workflow/UI.. :)

**Comment by mxmilkiib** [comment]
So a basic outline of something somewhere between BJumblr and BSEQuencer;

A grid, with the rows as channels and a CV output for each row. Waveform blocks (Impulse, Sine, Square, Triangle, Saw, Noise) can be dragged onto the spaces, with Control blocks etc as BSEQuencer.

Each block has it's own frequency-scale ratio/fraction. This is changed by (maybe) holding control and dragging or middle-wheel scrolling up or down on a block. This is displayed by both an alteration of the waveform displayed on the block and, when it isn't the default scale, a small green number in one corner of the block.

Maybe a 'link' tool to make adjacent waveform blocks continue the waveform and ratio from the first block when the first block has a ratio below 1.
