### ISSUE TITLE
Release 1.8.6 cannot build

### ISSUE THREAD

**Issue by AS383** [sjaehn/BSEQuencer#28]
Issues when try to build  release 1.8.6. I guess problems with macro PUGL_DEPRECATED_BY
[err_output.txt](https://github.com/sjaehn/BSEQuencer/files/5941752/err_output.txt)

**Comment by sjaehn** [comment]
Thanks for reporting. I guess you use default gcc / g++ for compiling. Which version?

**Comment by sjaehn** [comment]
... and you try to compile for an X11 system?

Quick and dirty fix: Compile with `make CPPFLAGS+=-DPUGL_DISABLE_DEPRECATED` instead of only `make`.
Note: I haven't tested this option and maybe other errors may occur.

I tested compiling with both gcc9 and gcc10 without any problems. Your error occurred within the included Pugl library (actual version, only empty `PUGL_API` definition). From the first look I would say the compiler doesn't know any enumerator attributes. I can trace back gcc support of enum attributes until gcc 6 (released 2016). Maybe @drobilla (https://github.com/lv2/pugl) knows something more.

**Comment by AS383** [comment]
Output with make CPPFLAGS+=-DPUGL_DISABLE_DEPRECATED 
[err_output_PUGL_DISABLE_DEPRECATED.txt](https://github.com/sjaehn/BSEQuencer/files/5949059/err_output_PUGL_DISABLE_DEPRECATED.txt)

GCC 5.5.0
OS Rosa Linux (kernel 5.10.4)

**Comment by sjaehn** [comment]
> Output with make CPPFLAGS+=-DPUGL_DISABLE_DEPRECATED

I was afraid of this.

> GCC 5.5.0

Thanks for info. GCC5 doesn't (officially) support enumerator attributes. At least GCC6 is required. Nevertheless, I'll look for a solution to get it running with older gcc versions.

**Comment by drobilla** [comment]
I think I will just finally remove the deprecated API, so it would be best to get your plugins building with PUGL_DISABLE_DEPRECATED.

**Comment by sjaehn** [comment]
@drobilla : Oops, I've overseen `PuglNativeWindow` which is within the '#ifndef PUGL_DISABLE_DEPRECATED` section but NOT labelled as deprecated: https://github.com/lv2/pugl/blob/master/include/pugl/pugl.h#L1296 . (After trying to label it too I know why you didn't do this ;-) )

@AS383 : I replaced `PuglNativeWindow` by `PuglNativeView` in 2f59fcf0b51683861c8d929a06f34b4ef164424d . Now I can compile with `make CPPFLAGS+=-DPUGL_DISABLE_DEPRECATED`. This should fix all but one compiler error for you.

The other one is a problem with C99 designated initializers. Fully supported only in GCC >= 8 or Clang >= 10 (what a shame ;-) ). Replaced in 6bd8a811b967e903f48fbeeeceea06390480d1fd . I hope it works now for you. Please let me know. Sorry I actually don't have older gcc to test it.

**Comment by drobilla** [comment]
Yeah, sorry, just some renaming there.  The overloading of "window" was really confusing so I'm trying to be consistent before sticking a 1.0 on the API and doing proper releases, etc.

**Comment by AS383** [comment]
Commit 6bd8a811b967e903f48fbeeeceea06390480d1fd solves all compile issues. Thanks.
